[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
auto-format = true
name = "nix"
formatter = { command = "alejandra" }

[[language]]
auto-format=true
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
[[language]]
auto-format=true
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
[[language]]
auto-format=true
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
[[language]]
auto-format=true
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
